image: golang:latest

before_script:
  - apt-get update -y
  - apt-get install zip -y
  - cd $GOPATH/src
  - mkdir -p gitlab.com/$CI_PROJECT_NAMESPACE
  - cd gitlab.com/$CI_PROJECT_NAMESPACE
  - ln -s $CI_PROJECT_DIR
  - cd $CI_PROJECT_NAME

stages:
  - build
  - test
  - deploy

testApp:
  stage: test
  script:
    - make test
  dependencies:
    - buildApp

buildApp:
  stage: build
  script:
    - make build
  artifacts:
    when: on_success
    paths:
      - bin

production:
  stage: deploy
  image: node:latest
  before_script:
    - npm config set prefix /usr/local
    - npm install -g serverless
    - npm install
  script:
    - export AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID"
    - export AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY"
    - serverless deploy --stage production --verbose --db_host="$DB_HOST" --db_passwd="$DB_PASSWD" --auth0_client_id="$AUTH0_CLIENT_ID" --auth0_secret="$AUTH0_SECRET"
  environment: production
  dependencies:
    - buildApp
  only:
    refs:
      - master
